# ArgoCD application configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-argo-application
  namespace: argocd

spec:
  project: default
  # Git repo source to link argocd to
  source:
    repoURL: git@github.com:Z11mm/terraform-argocd.git
    targetRevision: HEAD
    path: manifests/boutique
  # K8s cluster to make changes to
  destination:
    # endpoint for k8s api server/target k8s cluster. If namespace doesn't exist, argocd creates it.
    server: https://kubernetes.default.svc
    namespace: default  

  # Configure argocd to create the namespace specified in destination
  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true

    # Enable automatic sync - prevent direct changes to the cluster(selfHeal) and delete files in repo when deleted in cluster(prune)
    automated:
      selfHeal: true
